name: go-signal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        go: [ '1.17', '1.18', '1.19', '1.20', '1.21' ]
        include:
          - os: ubuntu-latest
            go-cache: ~/go/pkg/mod
            go-build: ~/.cache/go-build
          - os: macos-latest
            go-cache: ~/go/pkg/mod
            go-build: ~/Library/Caches/go-build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v -covermode=atomic -coverprofile=coverage.out

      - name: Cache builds
        uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.go-build }}
            ${{ matrix.go-cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
